// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/device_attributes.proto

package org.tensorflow.framework;

public interface DeviceAttributesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.DeviceAttributes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * Fully specified name of the device within a cluster.
   * </pre>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * Fully specified name of the device within a cluster.
   * </pre>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string device_type = 2;</code>
   *
   * <pre>
   * String representation of device_type.
   * </pre>
   */
  java.lang.String getDeviceType();
  /**
   * <code>optional string device_type = 2;</code>
   *
   * <pre>
   * String representation of device_type.
   * </pre>
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();

  /**
   * <code>optional int64 memory_limit = 4;</code>
   *
   * <pre>
   * Memory capacity of device in bytes.
   * </pre>
   */
  long getMemoryLimit();

  /**
   * <code>optional .tensorflow.DeviceLocality locality = 5;</code>
   *
   * <pre>
   * Platform-specific data about device that may be useful
   * for supporting efficient data transfers.
   * </pre>
   */
  boolean hasLocality();
  /**
   * <code>optional .tensorflow.DeviceLocality locality = 5;</code>
   *
   * <pre>
   * Platform-specific data about device that may be useful
   * for supporting efficient data transfers.
   * </pre>
   */
  org.tensorflow.framework.DeviceLocality getLocality();
  /**
   * <code>optional .tensorflow.DeviceLocality locality = 5;</code>
   *
   * <pre>
   * Platform-specific data about device that may be useful
   * for supporting efficient data transfers.
   * </pre>
   */
  org.tensorflow.framework.DeviceLocalityOrBuilder getLocalityOrBuilder();

  /**
   * <code>optional fixed64 incarnation = 6;</code>
   *
   * <pre>
   * A device is assigned a global unique number each time it is
   * initialized. "incarnation" should never be 0.
   * </pre>
   */
  long getIncarnation();

  /**
   * <code>optional string physical_device_desc = 7;</code>
   *
   * <pre>
   * String representation of the physical device that this device maps to.
   * </pre>
   */
  java.lang.String getPhysicalDeviceDesc();
  /**
   * <code>optional string physical_device_desc = 7;</code>
   *
   * <pre>
   * String representation of the physical device that this device maps to.
   * </pre>
   */
  com.google.protobuf.ByteString
      getPhysicalDeviceDescBytes();
}
