// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/function.proto

package org.tensorflow.framework;

/**
 * Protobuf type {@code tensorflow.FunctionDef}
 *
 * <pre>
 * A function can be instantiated when the runtime can bind every attr
 * with a value. When a GraphDef has a call to a function, it must
 * have binding for every attr defined in the signature.
 * TODO(zhifengc):
 *   * device spec, etc.
 * </pre>
 */
public  final class FunctionDef extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tensorflow.FunctionDef)
    FunctionDefOrBuilder {
  // Use FunctionDef.newBuilder() to construct.
  private FunctionDef(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FunctionDef() {
    nodeDef_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FunctionDef(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.tensorflow.framework.OpDef.Builder subBuilder = null;
            if (signature_ != null) {
              subBuilder = signature_.toBuilder();
            }
            signature_ = input.readMessage(org.tensorflow.framework.OpDef.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(signature_);
              signature_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              nodeDef_ = new java.util.ArrayList<org.tensorflow.framework.NodeDef>();
              mutable_bitField0_ |= 0x00000004;
            }
            nodeDef_.add(input.readMessage(org.tensorflow.framework.NodeDef.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              ret_ = com.google.protobuf.MapField.newMapField(
                  RetDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000008;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            ret = input.readMessage(
                RetDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            ret_.getMutableMap().put(ret.getKey(), ret.getValue());
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              attr_ = com.google.protobuf.MapField.newMapField(
                  AttrDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, org.tensorflow.framework.AttrValue>
            attr = input.readMessage(
                AttrDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            attr_.getMutableMap().put(attr.getKey(), attr.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        nodeDef_ = java.util.Collections.unmodifiableList(nodeDef_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 5:
        return internalGetAttr();
      case 4:
        return internalGetRet();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.framework.FunctionDef.class, org.tensorflow.framework.FunctionDef.Builder.class);
  }

  private int bitField0_;
  public static final int SIGNATURE_FIELD_NUMBER = 1;
  private org.tensorflow.framework.OpDef signature_;
  /**
   * <code>optional .tensorflow.OpDef signature = 1;</code>
   *
   * <pre>
   * The definition of the function's name, arguments, return values,
   * attrs etc.
   * </pre>
   */
  public boolean hasSignature() {
    return signature_ != null;
  }
  /**
   * <code>optional .tensorflow.OpDef signature = 1;</code>
   *
   * <pre>
   * The definition of the function's name, arguments, return values,
   * attrs etc.
   * </pre>
   */
  public org.tensorflow.framework.OpDef getSignature() {
    return signature_ == null ? org.tensorflow.framework.OpDef.getDefaultInstance() : signature_;
  }
  /**
   * <code>optional .tensorflow.OpDef signature = 1;</code>
   *
   * <pre>
   * The definition of the function's name, arguments, return values,
   * attrs etc.
   * </pre>
   */
  public org.tensorflow.framework.OpDefOrBuilder getSignatureOrBuilder() {
    return getSignature();
  }

  public static final int ATTR_FIELD_NUMBER = 5;
  private static final class AttrDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, org.tensorflow.framework.AttrValue> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, org.tensorflow.framework.AttrValue>newDefaultInstance(
                org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_AttrEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                org.tensorflow.framework.AttrValue.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, org.tensorflow.framework.AttrValue> attr_;
  private com.google.protobuf.MapField<java.lang.String, org.tensorflow.framework.AttrValue>
  internalGetAttr() {
    if (attr_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AttrDefaultEntryHolder.defaultEntry);
   }
    return attr_;
  }
  /**
   * <code>map&lt;string, .tensorflow.AttrValue&gt; attr = 5;</code>
   *
   * <pre>
   * Attributes specific to this function definition.
   * </pre>
   */

  public java.util.Map<java.lang.String, org.tensorflow.framework.AttrValue> getAttr() {
    return internalGetAttr().getMap();
  }

  public static final int NODE_DEF_FIELD_NUMBER = 3;
  private java.util.List<org.tensorflow.framework.NodeDef> nodeDef_;
  /**
   * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
   *
   * <pre>
   * By convention, "op" in node_def is resolved by consulting with a
   * user-defined library first. If not resolved, "func" is assumed to
   * be a builtin op.
   * </pre>
   */
  public java.util.List<org.tensorflow.framework.NodeDef> getNodeDefList() {
    return nodeDef_;
  }
  /**
   * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
   *
   * <pre>
   * By convention, "op" in node_def is resolved by consulting with a
   * user-defined library first. If not resolved, "func" is assumed to
   * be a builtin op.
   * </pre>
   */
  public java.util.List<? extends org.tensorflow.framework.NodeDefOrBuilder> 
      getNodeDefOrBuilderList() {
    return nodeDef_;
  }
  /**
   * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
   *
   * <pre>
   * By convention, "op" in node_def is resolved by consulting with a
   * user-defined library first. If not resolved, "func" is assumed to
   * be a builtin op.
   * </pre>
   */
  public int getNodeDefCount() {
    return nodeDef_.size();
  }
  /**
   * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
   *
   * <pre>
   * By convention, "op" in node_def is resolved by consulting with a
   * user-defined library first. If not resolved, "func" is assumed to
   * be a builtin op.
   * </pre>
   */
  public org.tensorflow.framework.NodeDef getNodeDef(int index) {
    return nodeDef_.get(index);
  }
  /**
   * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
   *
   * <pre>
   * By convention, "op" in node_def is resolved by consulting with a
   * user-defined library first. If not resolved, "func" is assumed to
   * be a builtin op.
   * </pre>
   */
  public org.tensorflow.framework.NodeDefOrBuilder getNodeDefOrBuilder(
      int index) {
    return nodeDef_.get(index);
  }

  public static final int RET_FIELD_NUMBER = 4;
  private static final class RetDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_RetEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> ret_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetRet() {
    if (ret_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          RetDefaultEntryHolder.defaultEntry);
   }
    return ret_;
  }
  /**
   * <code>map&lt;string, string&gt; ret = 4;</code>
   *
   * <pre>
   * A mapping from the output arg names from `signature` to the
   * outputs from `node_def` that should be returned by the function.
   * </pre>
   */

  public java.util.Map<java.lang.String, java.lang.String> getRet() {
    return internalGetRet().getMap();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (signature_ != null) {
      output.writeMessage(1, getSignature());
    }
    for (int i = 0; i < nodeDef_.size(); i++) {
      output.writeMessage(3, nodeDef_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetRet().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      ret = RetDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      output.writeMessage(4, ret);
    }
    for (java.util.Map.Entry<java.lang.String, org.tensorflow.framework.AttrValue> entry
         : internalGetAttr().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, org.tensorflow.framework.AttrValue>
      attr = AttrDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      output.writeMessage(5, attr);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (signature_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSignature());
    }
    for (int i = 0; i < nodeDef_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, nodeDef_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetRet().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      ret = RetDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, ret);
    }
    for (java.util.Map.Entry<java.lang.String, org.tensorflow.framework.AttrValue> entry
         : internalGetAttr().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, org.tensorflow.framework.AttrValue>
      attr = AttrDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, attr);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static org.tensorflow.framework.FunctionDef parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.FunctionDef parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.FunctionDef parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.FunctionDef parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.FunctionDef parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.tensorflow.framework.FunctionDef parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.tensorflow.framework.FunctionDef parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.tensorflow.framework.FunctionDef parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.tensorflow.framework.FunctionDef parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.tensorflow.framework.FunctionDef parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.framework.FunctionDef prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.FunctionDef}
   *
   * <pre>
   * A function can be instantiated when the runtime can bind every attr
   * with a value. When a GraphDef has a call to a function, it must
   * have binding for every attr defined in the signature.
   * TODO(zhifengc):
   *   * device spec, etc.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.FunctionDef)
      org.tensorflow.framework.FunctionDefOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetAttr();
        case 4:
          return internalGetRet();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableAttr();
        case 4:
          return internalGetMutableRet();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.framework.FunctionDef.class, org.tensorflow.framework.FunctionDef.Builder.class);
    }

    // Construct using org.tensorflow.framework.FunctionDef.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getNodeDefFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (signatureBuilder_ == null) {
        signature_ = null;
      } else {
        signature_ = null;
        signatureBuilder_ = null;
      }
      internalGetMutableAttr().clear();
      if (nodeDefBuilder_ == null) {
        nodeDef_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        nodeDefBuilder_.clear();
      }
      internalGetMutableRet().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.framework.FunctionProtos.internal_static_tensorflow_FunctionDef_descriptor;
    }

    public org.tensorflow.framework.FunctionDef getDefaultInstanceForType() {
      return org.tensorflow.framework.FunctionDef.getDefaultInstance();
    }

    public org.tensorflow.framework.FunctionDef build() {
      org.tensorflow.framework.FunctionDef result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.tensorflow.framework.FunctionDef buildPartial() {
      org.tensorflow.framework.FunctionDef result = new org.tensorflow.framework.FunctionDef(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (signatureBuilder_ == null) {
        result.signature_ = signature_;
      } else {
        result.signature_ = signatureBuilder_.build();
      }
      result.attr_ = internalGetAttr();
      result.attr_.makeImmutable();
      if (nodeDefBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          nodeDef_ = java.util.Collections.unmodifiableList(nodeDef_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.nodeDef_ = nodeDef_;
      } else {
        result.nodeDef_ = nodeDefBuilder_.build();
      }
      result.ret_ = internalGetRet();
      result.ret_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.framework.FunctionDef) {
        return mergeFrom((org.tensorflow.framework.FunctionDef)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.framework.FunctionDef other) {
      if (other == org.tensorflow.framework.FunctionDef.getDefaultInstance()) return this;
      if (other.hasSignature()) {
        mergeSignature(other.getSignature());
      }
      internalGetMutableAttr().mergeFrom(
          other.internalGetAttr());
      if (nodeDefBuilder_ == null) {
        if (!other.nodeDef_.isEmpty()) {
          if (nodeDef_.isEmpty()) {
            nodeDef_ = other.nodeDef_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureNodeDefIsMutable();
            nodeDef_.addAll(other.nodeDef_);
          }
          onChanged();
        }
      } else {
        if (!other.nodeDef_.isEmpty()) {
          if (nodeDefBuilder_.isEmpty()) {
            nodeDefBuilder_.dispose();
            nodeDefBuilder_ = null;
            nodeDef_ = other.nodeDef_;
            bitField0_ = (bitField0_ & ~0x00000004);
            nodeDefBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getNodeDefFieldBuilder() : null;
          } else {
            nodeDefBuilder_.addAllMessages(other.nodeDef_);
          }
        }
      }
      internalGetMutableRet().mergeFrom(
          other.internalGetRet());
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tensorflow.framework.FunctionDef parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tensorflow.framework.FunctionDef) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.tensorflow.framework.OpDef signature_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        org.tensorflow.framework.OpDef, org.tensorflow.framework.OpDef.Builder, org.tensorflow.framework.OpDefOrBuilder> signatureBuilder_;
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public boolean hasSignature() {
      return signatureBuilder_ != null || signature_ != null;
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public org.tensorflow.framework.OpDef getSignature() {
      if (signatureBuilder_ == null) {
        return signature_ == null ? org.tensorflow.framework.OpDef.getDefaultInstance() : signature_;
      } else {
        return signatureBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public Builder setSignature(org.tensorflow.framework.OpDef value) {
      if (signatureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        signature_ = value;
        onChanged();
      } else {
        signatureBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public Builder setSignature(
        org.tensorflow.framework.OpDef.Builder builderForValue) {
      if (signatureBuilder_ == null) {
        signature_ = builderForValue.build();
        onChanged();
      } else {
        signatureBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public Builder mergeSignature(org.tensorflow.framework.OpDef value) {
      if (signatureBuilder_ == null) {
        if (signature_ != null) {
          signature_ =
            org.tensorflow.framework.OpDef.newBuilder(signature_).mergeFrom(value).buildPartial();
        } else {
          signature_ = value;
        }
        onChanged();
      } else {
        signatureBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public Builder clearSignature() {
      if (signatureBuilder_ == null) {
        signature_ = null;
        onChanged();
      } else {
        signature_ = null;
        signatureBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public org.tensorflow.framework.OpDef.Builder getSignatureBuilder() {
      
      onChanged();
      return getSignatureFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    public org.tensorflow.framework.OpDefOrBuilder getSignatureOrBuilder() {
      if (signatureBuilder_ != null) {
        return signatureBuilder_.getMessageOrBuilder();
      } else {
        return signature_ == null ?
            org.tensorflow.framework.OpDef.getDefaultInstance() : signature_;
      }
    }
    /**
     * <code>optional .tensorflow.OpDef signature = 1;</code>
     *
     * <pre>
     * The definition of the function's name, arguments, return values,
     * attrs etc.
     * </pre>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.tensorflow.framework.OpDef, org.tensorflow.framework.OpDef.Builder, org.tensorflow.framework.OpDefOrBuilder> 
        getSignatureFieldBuilder() {
      if (signatureBuilder_ == null) {
        signatureBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.tensorflow.framework.OpDef, org.tensorflow.framework.OpDef.Builder, org.tensorflow.framework.OpDefOrBuilder>(
                getSignature(),
                getParentForChildren(),
                isClean());
        signature_ = null;
      }
      return signatureBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, org.tensorflow.framework.AttrValue> attr_;
    private com.google.protobuf.MapField<java.lang.String, org.tensorflow.framework.AttrValue>
    internalGetAttr() {
      if (attr_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttrDefaultEntryHolder.defaultEntry);
     }
      return attr_;
    }
    private com.google.protobuf.MapField<java.lang.String, org.tensorflow.framework.AttrValue>
    internalGetMutableAttr() {
      onChanged();;
      if (attr_ == null) {
        attr_ = com.google.protobuf.MapField.newMapField(
            AttrDefaultEntryHolder.defaultEntry);
      }
      if (!attr_.isMutable()) {
        attr_ = attr_.copy();
      }
      return attr_;
    }
    /**
     * <code>map&lt;string, .tensorflow.AttrValue&gt; attr = 5;</code>
     *
     * <pre>
     * Attributes specific to this function definition.
     * </pre>
     */
    public java.util.Map<java.lang.String, org.tensorflow.framework.AttrValue> getAttr() {
      return internalGetAttr().getMap();
    }
    /**
     * <code>map&lt;string, .tensorflow.AttrValue&gt; attr = 5;</code>
     *
     * <pre>
     * Attributes specific to this function definition.
     * </pre>
     */
    public java.util.Map<java.lang.String, org.tensorflow.framework.AttrValue>
    getMutableAttr() {
      return internalGetMutableAttr().getMutableMap();
    }
    /**
     * <code>map&lt;string, .tensorflow.AttrValue&gt; attr = 5;</code>
     *
     * <pre>
     * Attributes specific to this function definition.
     * </pre>
     */
    public Builder putAllAttr(
        java.util.Map<java.lang.String, org.tensorflow.framework.AttrValue> values) {
      getMutableAttr().putAll(values);
      return this;
    }

    private java.util.List<org.tensorflow.framework.NodeDef> nodeDef_ =
      java.util.Collections.emptyList();
    private void ensureNodeDefIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        nodeDef_ = new java.util.ArrayList<org.tensorflow.framework.NodeDef>(nodeDef_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.tensorflow.framework.NodeDef, org.tensorflow.framework.NodeDef.Builder, org.tensorflow.framework.NodeDefOrBuilder> nodeDefBuilder_;

    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public java.util.List<org.tensorflow.framework.NodeDef> getNodeDefList() {
      if (nodeDefBuilder_ == null) {
        return java.util.Collections.unmodifiableList(nodeDef_);
      } else {
        return nodeDefBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public int getNodeDefCount() {
      if (nodeDefBuilder_ == null) {
        return nodeDef_.size();
      } else {
        return nodeDefBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public org.tensorflow.framework.NodeDef getNodeDef(int index) {
      if (nodeDefBuilder_ == null) {
        return nodeDef_.get(index);
      } else {
        return nodeDefBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public Builder setNodeDef(
        int index, org.tensorflow.framework.NodeDef value) {
      if (nodeDefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodeDefIsMutable();
        nodeDef_.set(index, value);
        onChanged();
      } else {
        nodeDefBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public Builder setNodeDef(
        int index, org.tensorflow.framework.NodeDef.Builder builderForValue) {
      if (nodeDefBuilder_ == null) {
        ensureNodeDefIsMutable();
        nodeDef_.set(index, builderForValue.build());
        onChanged();
      } else {
        nodeDefBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public Builder addNodeDef(org.tensorflow.framework.NodeDef value) {
      if (nodeDefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodeDefIsMutable();
        nodeDef_.add(value);
        onChanged();
      } else {
        nodeDefBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public Builder addNodeDef(
        int index, org.tensorflow.framework.NodeDef value) {
      if (nodeDefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodeDefIsMutable();
        nodeDef_.add(index, value);
        onChanged();
      } else {
        nodeDefBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public Builder addNodeDef(
        org.tensorflow.framework.NodeDef.Builder builderForValue) {
      if (nodeDefBuilder_ == null) {
        ensureNodeDefIsMutable();
        nodeDef_.add(builderForValue.build());
        onChanged();
      } else {
        nodeDefBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public Builder addNodeDef(
        int index, org.tensorflow.framework.NodeDef.Builder builderForValue) {
      if (nodeDefBuilder_ == null) {
        ensureNodeDefIsMutable();
        nodeDef_.add(index, builderForValue.build());
        onChanged();
      } else {
        nodeDefBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public Builder addAllNodeDef(
        java.lang.Iterable<? extends org.tensorflow.framework.NodeDef> values) {
      if (nodeDefBuilder_ == null) {
        ensureNodeDefIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nodeDef_);
        onChanged();
      } else {
        nodeDefBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public Builder clearNodeDef() {
      if (nodeDefBuilder_ == null) {
        nodeDef_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        nodeDefBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public Builder removeNodeDef(int index) {
      if (nodeDefBuilder_ == null) {
        ensureNodeDefIsMutable();
        nodeDef_.remove(index);
        onChanged();
      } else {
        nodeDefBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public org.tensorflow.framework.NodeDef.Builder getNodeDefBuilder(
        int index) {
      return getNodeDefFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public org.tensorflow.framework.NodeDefOrBuilder getNodeDefOrBuilder(
        int index) {
      if (nodeDefBuilder_ == null) {
        return nodeDef_.get(index);  } else {
        return nodeDefBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public java.util.List<? extends org.tensorflow.framework.NodeDefOrBuilder> 
         getNodeDefOrBuilderList() {
      if (nodeDefBuilder_ != null) {
        return nodeDefBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(nodeDef_);
      }
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public org.tensorflow.framework.NodeDef.Builder addNodeDefBuilder() {
      return getNodeDefFieldBuilder().addBuilder(
          org.tensorflow.framework.NodeDef.getDefaultInstance());
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public org.tensorflow.framework.NodeDef.Builder addNodeDefBuilder(
        int index) {
      return getNodeDefFieldBuilder().addBuilder(
          index, org.tensorflow.framework.NodeDef.getDefaultInstance());
    }
    /**
     * <code>repeated .tensorflow.NodeDef node_def = 3;</code>
     *
     * <pre>
     * By convention, "op" in node_def is resolved by consulting with a
     * user-defined library first. If not resolved, "func" is assumed to
     * be a builtin op.
     * </pre>
     */
    public java.util.List<org.tensorflow.framework.NodeDef.Builder> 
         getNodeDefBuilderList() {
      return getNodeDefFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.tensorflow.framework.NodeDef, org.tensorflow.framework.NodeDef.Builder, org.tensorflow.framework.NodeDefOrBuilder> 
        getNodeDefFieldBuilder() {
      if (nodeDefBuilder_ == null) {
        nodeDefBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.tensorflow.framework.NodeDef, org.tensorflow.framework.NodeDef.Builder, org.tensorflow.framework.NodeDefOrBuilder>(
                nodeDef_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        nodeDef_ = null;
      }
      return nodeDefBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> ret_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetRet() {
      if (ret_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            RetDefaultEntryHolder.defaultEntry);
     }
      return ret_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableRet() {
      onChanged();;
      if (ret_ == null) {
        ret_ = com.google.protobuf.MapField.newMapField(
            RetDefaultEntryHolder.defaultEntry);
      }
      if (!ret_.isMutable()) {
        ret_ = ret_.copy();
      }
      return ret_;
    }
    /**
     * <code>map&lt;string, string&gt; ret = 4;</code>
     *
     * <pre>
     * A mapping from the output arg names from `signature` to the
     * outputs from `node_def` that should be returned by the function.
     * </pre>
     */
    public java.util.Map<java.lang.String, java.lang.String> getRet() {
      return internalGetRet().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; ret = 4;</code>
     *
     * <pre>
     * A mapping from the output arg names from `signature` to the
     * outputs from `node_def` that should be returned by the function.
     * </pre>
     */
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableRet() {
      return internalGetMutableRet().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; ret = 4;</code>
     *
     * <pre>
     * A mapping from the output arg names from `signature` to the
     * outputs from `node_def` that should be returned by the function.
     * </pre>
     */
    public Builder putAllRet(
        java.util.Map<java.lang.String, java.lang.String> values) {
      getMutableRet().putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.FunctionDef)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.FunctionDef)
  private static final org.tensorflow.framework.FunctionDef DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.framework.FunctionDef();
  }

  public static org.tensorflow.framework.FunctionDef getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FunctionDef>
      PARSER = new com.google.protobuf.AbstractParser<FunctionDef>() {
    public FunctionDef parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new FunctionDef(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<FunctionDef> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FunctionDef> getParserForType() {
    return PARSER;
  }

  public org.tensorflow.framework.FunctionDef getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

