// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/function.proto

package org.tensorflow.framework;

public interface GradientDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.GradientDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string function_name = 1;</code>
   *
   * <pre>
   * The function name.
   * </pre>
   */
  java.lang.String getFunctionName();
  /**
   * <code>optional string function_name = 1;</code>
   *
   * <pre>
   * The function name.
   * </pre>
   */
  com.google.protobuf.ByteString
      getFunctionNameBytes();

  /**
   * <code>optional string gradient_func = 2;</code>
   *
   * <pre>
   * The gradient function's name.
   * </pre>
   */
  java.lang.String getGradientFunc();
  /**
   * <code>optional string gradient_func = 2;</code>
   *
   * <pre>
   * The gradient function's name.
   * </pre>
   */
  com.google.protobuf.ByteString
      getGradientFuncBytes();
}
