// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/log_memory.proto

package org.tensorflow.framework;

public interface MemoryLogStepOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.MemoryLogStep)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 step_id = 1;</code>
   *
   * <pre>
   * Process-unique step id.
   * </pre>
   */
  long getStepId();

  /**
   * <code>optional string handle = 2;</code>
   *
   * <pre>
   * Handle describing the feeds and fetches of the step.
   * </pre>
   */
  java.lang.String getHandle();
  /**
   * <code>optional string handle = 2;</code>
   *
   * <pre>
   * Handle describing the feeds and fetches of the step.
   * </pre>
   */
  com.google.protobuf.ByteString
      getHandleBytes();
}
