// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/log_memory.proto

package org.tensorflow.framework;

public interface MemoryLogRawAllocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.MemoryLogRawAllocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 step_id = 1;</code>
   *
   * <pre>
   * Process-unique step id.
   * </pre>
   */
  long getStepId();

  /**
   * <code>optional string operation = 2;</code>
   *
   * <pre>
   * Name of the operation making the allocation.
   * </pre>
   */
  java.lang.String getOperation();
  /**
   * <code>optional string operation = 2;</code>
   *
   * <pre>
   * Name of the operation making the allocation.
   * </pre>
   */
  com.google.protobuf.ByteString
      getOperationBytes();

  /**
   * <code>optional int64 num_bytes = 3;</code>
   *
   * <pre>
   * Number of bytes in the allocation.
   * </pre>
   */
  long getNumBytes();

  /**
   * <code>optional uint64 ptr = 4;</code>
   *
   * <pre>
   * Address of the allocation.
   * </pre>
   */
  long getPtr();

  /**
   * <code>optional int64 allocation_id = 5;</code>
   *
   * <pre>
   * Id of the tensor buffer being allocated, used to match to a
   * corresponding deallocation.
   * </pre>
   */
  long getAllocationId();

  /**
   * <code>optional string allocator_name = 6;</code>
   *
   * <pre>
   * Name of the allocator used.
   * </pre>
   */
  java.lang.String getAllocatorName();
  /**
   * <code>optional string allocator_name = 6;</code>
   *
   * <pre>
   * Name of the allocator used.
   * </pre>
   */
  com.google.protobuf.ByteString
      getAllocatorNameBytes();
}
