// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/log_memory.proto

package org.tensorflow.framework;

public interface MemoryLogTensorAllocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.MemoryLogTensorAllocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 step_id = 1;</code>
   *
   * <pre>
   * Process-unique step id.
   * </pre>
   */
  long getStepId();

  /**
   * <code>optional string kernel_name = 2;</code>
   *
   * <pre>
   * Name of the kernel making the allocation as set in GraphDef,
   * e.g., "affine2/weights/Assign".
   * </pre>
   */
  java.lang.String getKernelName();
  /**
   * <code>optional string kernel_name = 2;</code>
   *
   * <pre>
   * Name of the kernel making the allocation as set in GraphDef,
   * e.g., "affine2/weights/Assign".
   * </pre>
   */
  com.google.protobuf.ByteString
      getKernelNameBytes();

  /**
   * <code>optional .tensorflow.TensorDescription tensor = 3;</code>
   *
   * <pre>
   * Allocated tensor details.
   * </pre>
   */
  boolean hasTensor();
  /**
   * <code>optional .tensorflow.TensorDescription tensor = 3;</code>
   *
   * <pre>
   * Allocated tensor details.
   * </pre>
   */
  org.tensorflow.framework.TensorDescription getTensor();
  /**
   * <code>optional .tensorflow.TensorDescription tensor = 3;</code>
   *
   * <pre>
   * Allocated tensor details.
   * </pre>
   */
  org.tensorflow.framework.TensorDescriptionOrBuilder getTensorOrBuilder();
}
