// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/log_memory.proto

package org.tensorflow.framework;

public interface MemoryLogTensorDeallocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.MemoryLogTensorDeallocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 allocation_id = 1;</code>
   *
   * <pre>
   * Id of the tensor buffer being deallocated, used to match to a
   * corresponding allocation.
   * </pre>
   */
  long getAllocationId();

  /**
   * <code>optional string allocator_name = 2;</code>
   *
   * <pre>
   * Name of the allocator used.
   * </pre>
   */
  java.lang.String getAllocatorName();
  /**
   * <code>optional string allocator_name = 2;</code>
   *
   * <pre>
   * Name of the allocator used.
   * </pre>
   */
  com.google.protobuf.ByteString
      getAllocatorNameBytes();
}
