// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/op_def.proto

package org.tensorflow.framework;

public interface OpDeprecationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.OpDeprecation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 version = 1;</code>
   *
   * <pre>
   * First GraphDef version at which the op is disallowed.
   * </pre>
   */
  int getVersion();

  /**
   * <code>optional string explanation = 2;</code>
   *
   * <pre>
   * Explanation of why it was deprecated and what to use instead.
   * </pre>
   */
  java.lang.String getExplanation();
  /**
   * <code>optional string explanation = 2;</code>
   *
   * <pre>
   * Explanation of why it was deprecated and what to use instead.
   * </pre>
   */
  com.google.protobuf.ByteString
      getExplanationBytes();
}
