// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/remote_fused_graph_execute_info.proto

package org.tensorflow.framework;

public interface RemoteFusedGraphExecuteInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.RemoteFusedGraphExecuteInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .tensorflow.GraphDef remote_graph = 1;</code>
   *
   * <pre>
   * Definition of remote graph
   * </pre>
   */
  boolean hasRemoteGraph();
  /**
   * <code>optional .tensorflow.GraphDef remote_graph = 1;</code>
   *
   * <pre>
   * Definition of remote graph
   * </pre>
   */
  org.tensorflow.framework.GraphDef getRemoteGraph();
  /**
   * <code>optional .tensorflow.GraphDef remote_graph = 1;</code>
   *
   * <pre>
   * Definition of remote graph
   * </pre>
   */
  org.tensorflow.framework.GraphDefOrBuilder getRemoteGraphOrBuilder();

  /**
   * <code>repeated string graph_input_node_name = 2;</code>
   *
   * <pre>
   * Remote fused graph input node name
   * </pre>
   */
  com.google.protobuf.ProtocolStringList
      getGraphInputNodeNameList();
  /**
   * <code>repeated string graph_input_node_name = 2;</code>
   *
   * <pre>
   * Remote fused graph input node name
   * </pre>
   */
  int getGraphInputNodeNameCount();
  /**
   * <code>repeated string graph_input_node_name = 2;</code>
   *
   * <pre>
   * Remote fused graph input node name
   * </pre>
   */
  java.lang.String getGraphInputNodeName(int index);
  /**
   * <code>repeated string graph_input_node_name = 2;</code>
   *
   * <pre>
   * Remote fused graph input node name
   * </pre>
   */
  com.google.protobuf.ByteString
      getGraphInputNodeNameBytes(int index);

  /**
   * <code>repeated string graph_output_node_name = 3;</code>
   *
   * <pre>
   * Remote fused graph output node name
   * </pre>
   */
  com.google.protobuf.ProtocolStringList
      getGraphOutputNodeNameList();
  /**
   * <code>repeated string graph_output_node_name = 3;</code>
   *
   * <pre>
   * Remote fused graph output node name
   * </pre>
   */
  int getGraphOutputNodeNameCount();
  /**
   * <code>repeated string graph_output_node_name = 3;</code>
   *
   * <pre>
   * Remote fused graph output node name
   * </pre>
   */
  java.lang.String getGraphOutputNodeName(int index);
  /**
   * <code>repeated string graph_output_node_name = 3;</code>
   *
   * <pre>
   * Remote fused graph output node name
   * </pre>
   */
  com.google.protobuf.ByteString
      getGraphOutputNodeNameBytes(int index);

  /**
   * <code>optional string executor_name = 4;</code>
   *
   * <pre>
   * Executor's name
   * </pre>
   */
  java.lang.String getExecutorName();
  /**
   * <code>optional string executor_name = 4;</code>
   *
   * <pre>
   * Executor's name
   * </pre>
   */
  com.google.protobuf.ByteString
      getExecutorNameBytes();

  /**
   * <code>optional bytes serialized_executor_parameters = 5;</code>
   *
   * <pre>
   * Optional: Parameters given to the executor
   * </pre>
   */
  com.google.protobuf.ByteString getSerializedExecutorParameters();

  /**
   * <code>repeated .tensorflow.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto default_graph_input_tensor_shape = 6;</code>
   *
   * <pre>
   * Optional: Default graph input tensor shape used to allocate memory
   * before executing op
   * </pre>
   */
  java.util.List<org.tensorflow.framework.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto> 
      getDefaultGraphInputTensorShapeList();
  /**
   * <code>repeated .tensorflow.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto default_graph_input_tensor_shape = 6;</code>
   *
   * <pre>
   * Optional: Default graph input tensor shape used to allocate memory
   * before executing op
   * </pre>
   */
  org.tensorflow.framework.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto getDefaultGraphInputTensorShape(int index);
  /**
   * <code>repeated .tensorflow.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto default_graph_input_tensor_shape = 6;</code>
   *
   * <pre>
   * Optional: Default graph input tensor shape used to allocate memory
   * before executing op
   * </pre>
   */
  int getDefaultGraphInputTensorShapeCount();
  /**
   * <code>repeated .tensorflow.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto default_graph_input_tensor_shape = 6;</code>
   *
   * <pre>
   * Optional: Default graph input tensor shape used to allocate memory
   * before executing op
   * </pre>
   */
  java.util.List<? extends org.tensorflow.framework.RemoteFusedGraphExecuteInfo.TensorShapeTypeProtoOrBuilder> 
      getDefaultGraphInputTensorShapeOrBuilderList();
  /**
   * <code>repeated .tensorflow.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto default_graph_input_tensor_shape = 6;</code>
   *
   * <pre>
   * Optional: Default graph input tensor shape used to allocate memory
   * before executing op
   * </pre>
   */
  org.tensorflow.framework.RemoteFusedGraphExecuteInfo.TensorShapeTypeProtoOrBuilder getDefaultGraphInputTensorShapeOrBuilder(
      int index);

  /**
   * <code>repeated .tensorflow.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto default_graph_output_tensor_shape = 7;</code>
   *
   * <pre>
   * Optional: Default graph input tensor shape used to allocate memory
   * before executing op
   * TODO(satok): Remote output tensor shape once shape information is stored
   * in NodeDef
   * </pre>
   */
  java.util.List<org.tensorflow.framework.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto> 
      getDefaultGraphOutputTensorShapeList();
  /**
   * <code>repeated .tensorflow.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto default_graph_output_tensor_shape = 7;</code>
   *
   * <pre>
   * Optional: Default graph input tensor shape used to allocate memory
   * before executing op
   * TODO(satok): Remote output tensor shape once shape information is stored
   * in NodeDef
   * </pre>
   */
  org.tensorflow.framework.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto getDefaultGraphOutputTensorShape(int index);
  /**
   * <code>repeated .tensorflow.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto default_graph_output_tensor_shape = 7;</code>
   *
   * <pre>
   * Optional: Default graph input tensor shape used to allocate memory
   * before executing op
   * TODO(satok): Remote output tensor shape once shape information is stored
   * in NodeDef
   * </pre>
   */
  int getDefaultGraphOutputTensorShapeCount();
  /**
   * <code>repeated .tensorflow.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto default_graph_output_tensor_shape = 7;</code>
   *
   * <pre>
   * Optional: Default graph input tensor shape used to allocate memory
   * before executing op
   * TODO(satok): Remote output tensor shape once shape information is stored
   * in NodeDef
   * </pre>
   */
  java.util.List<? extends org.tensorflow.framework.RemoteFusedGraphExecuteInfo.TensorShapeTypeProtoOrBuilder> 
      getDefaultGraphOutputTensorShapeOrBuilderList();
  /**
   * <code>repeated .tensorflow.RemoteFusedGraphExecuteInfo.TensorShapeTypeProto default_graph_output_tensor_shape = 7;</code>
   *
   * <pre>
   * Optional: Default graph input tensor shape used to allocate memory
   * before executing op
   * TODO(satok): Remote output tensor shape once shape information is stored
   * in NodeDef
   * </pre>
   */
  org.tensorflow.framework.RemoteFusedGraphExecuteInfo.TensorShapeTypeProtoOrBuilder getDefaultGraphOutputTensorShapeOrBuilder(
      int index);
}
