// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/resource_handle.proto

package org.tensorflow.framework;

public interface ResourceHandleProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.ResourceHandleProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string device = 1;</code>
   *
   * <pre>
   * Unique name for the device containing the resource.
   * </pre>
   */
  java.lang.String getDevice();
  /**
   * <code>optional string device = 1;</code>
   *
   * <pre>
   * Unique name for the device containing the resource.
   * </pre>
   */
  com.google.protobuf.ByteString
      getDeviceBytes();

  /**
   * <code>optional string container = 2;</code>
   *
   * <pre>
   * Container in which this resource is placed.
   * </pre>
   */
  java.lang.String getContainer();
  /**
   * <code>optional string container = 2;</code>
   *
   * <pre>
   * Container in which this resource is placed.
   * </pre>
   */
  com.google.protobuf.ByteString
      getContainerBytes();

  /**
   * <code>optional string name = 3;</code>
   *
   * <pre>
   * Unique name of this resource.
   * </pre>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 3;</code>
   *
   * <pre>
   * Unique name of this resource.
   * </pre>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional uint64 hash_code = 4;</code>
   *
   * <pre>
   * Hash code for the type of the resource. Is only valid in the same device
   * and in the same execution.
   * </pre>
   */
  long getHashCode();

  /**
   * <code>optional string maybe_type_name = 5;</code>
   *
   * <pre>
   * For debug-only, the name of the type pointed to by this handle, if
   * available.
   * </pre>
   */
  java.lang.String getMaybeTypeName();
  /**
   * <code>optional string maybe_type_name = 5;</code>
   *
   * <pre>
   * For debug-only, the name of the type pointed to by this handle, if
   * available.
   * </pre>
   */
  com.google.protobuf.ByteString
      getMaybeTypeNameBytes();
}
