// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/summary.proto

package org.tensorflow.framework;

public interface SummaryMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.SummaryMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .tensorflow.SummaryMetadata.PluginData plugin_data = 1;</code>
   *
   * <pre>
   * Data that associates a summary with a certain plugin.
   * </pre>
   */
  boolean hasPluginData();
  /**
   * <code>optional .tensorflow.SummaryMetadata.PluginData plugin_data = 1;</code>
   *
   * <pre>
   * Data that associates a summary with a certain plugin.
   * </pre>
   */
  org.tensorflow.framework.SummaryMetadata.PluginData getPluginData();
  /**
   * <code>optional .tensorflow.SummaryMetadata.PluginData plugin_data = 1;</code>
   *
   * <pre>
   * Data that associates a summary with a certain plugin.
   * </pre>
   */
  org.tensorflow.framework.SummaryMetadata.PluginDataOrBuilder getPluginDataOrBuilder();

  /**
   * <code>optional string display_name = 2;</code>
   *
   * <pre>
   * Display name for viewing in TensorBoard.
   * </pre>
   */
  java.lang.String getDisplayName();
  /**
   * <code>optional string display_name = 2;</code>
   *
   * <pre>
   * Display name for viewing in TensorBoard.
   * </pre>
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <code>optional string summary_description = 3;</code>
   *
   * <pre>
   * Longform readable description of the summary sequence. Markdown supported.
   * </pre>
   */
  java.lang.String getSummaryDescription();
  /**
   * <code>optional string summary_description = 3;</code>
   *
   * <pre>
   * Longform readable description of the summary sequence. Markdown supported.
   * </pre>
   */
  com.google.protobuf.ByteString
      getSummaryDescriptionBytes();
}
