// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/summary.proto

package org.tensorflow.framework;

public interface SummaryDescriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.SummaryDescription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string type_hint = 1;</code>
   *
   * <pre>
   * Hint on how plugins should process the data in this series.
   * Supported values include "scalar", "histogram", "image", "audio"
   * </pre>
   */
  java.lang.String getTypeHint();
  /**
   * <code>optional string type_hint = 1;</code>
   *
   * <pre>
   * Hint on how plugins should process the data in this series.
   * Supported values include "scalar", "histogram", "image", "audio"
   * </pre>
   */
  com.google.protobuf.ByteString
      getTypeHintBytes();
}
