// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/summary.proto

package org.tensorflow.framework;

/**
 * Protobuf type {@code tensorflow.SummaryMetadata}
 *
 * <pre>
 * A SummaryMetadata encapsulates information on which plugins are able to make
 * use of a certain summary value.
 * </pre>
 */
public  final class SummaryMetadata extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tensorflow.SummaryMetadata)
    SummaryMetadataOrBuilder {
  // Use SummaryMetadata.newBuilder() to construct.
  private SummaryMetadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SummaryMetadata() {
    displayName_ = "";
    summaryDescription_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SummaryMetadata(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.tensorflow.framework.SummaryMetadata.PluginData.Builder subBuilder = null;
            if (pluginData_ != null) {
              subBuilder = pluginData_.toBuilder();
            }
            pluginData_ = input.readMessage(org.tensorflow.framework.SummaryMetadata.PluginData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pluginData_);
              pluginData_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            displayName_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            summaryDescription_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.framework.SummaryProtos.internal_static_tensorflow_SummaryMetadata_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.framework.SummaryProtos.internal_static_tensorflow_SummaryMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.framework.SummaryMetadata.class, org.tensorflow.framework.SummaryMetadata.Builder.class);
  }

  public interface PluginDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.SummaryMetadata.PluginData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string plugin_name = 1;</code>
     *
     * <pre>
     * The name of the plugin this data pertains to.
     * </pre>
     */
    java.lang.String getPluginName();
    /**
     * <code>optional string plugin_name = 1;</code>
     *
     * <pre>
     * The name of the plugin this data pertains to.
     * </pre>
     */
    com.google.protobuf.ByteString
        getPluginNameBytes();

    /**
     * <code>optional bytes content = 2;</code>
     *
     * <pre>
     * The content to store for the plugin. The best practice is for this to be
     * a binary serialized protocol buffer.
     * </pre>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code tensorflow.SummaryMetadata.PluginData}
   */
  public  static final class PluginData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tensorflow.SummaryMetadata.PluginData)
      PluginDataOrBuilder {
    // Use PluginData.newBuilder() to construct.
    private PluginData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PluginData() {
      pluginName_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PluginData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              pluginName_ = s;
              break;
            }
            case 18: {

              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.framework.SummaryProtos.internal_static_tensorflow_SummaryMetadata_PluginData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.framework.SummaryProtos.internal_static_tensorflow_SummaryMetadata_PluginData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.framework.SummaryMetadata.PluginData.class, org.tensorflow.framework.SummaryMetadata.PluginData.Builder.class);
    }

    public static final int PLUGIN_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object pluginName_;
    /**
     * <code>optional string plugin_name = 1;</code>
     *
     * <pre>
     * The name of the plugin this data pertains to.
     * </pre>
     */
    public java.lang.String getPluginName() {
      java.lang.Object ref = pluginName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pluginName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string plugin_name = 1;</code>
     *
     * <pre>
     * The name of the plugin this data pertains to.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPluginNameBytes() {
      java.lang.Object ref = pluginName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pluginName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>optional bytes content = 2;</code>
     *
     * <pre>
     * The content to store for the plugin. The best practice is for this to be
     * a binary serialized protocol buffer.
     * </pre>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPluginNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, pluginName_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(2, content_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPluginNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, pluginName_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.tensorflow.framework.SummaryMetadata.PluginData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tensorflow.framework.SummaryMetadata.PluginData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tensorflow.framework.SummaryMetadata.PluginData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tensorflow.framework.SummaryMetadata.PluginData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tensorflow.framework.SummaryMetadata.PluginData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tensorflow.framework.SummaryMetadata.PluginData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tensorflow.framework.SummaryMetadata.PluginData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tensorflow.framework.SummaryMetadata.PluginData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tensorflow.framework.SummaryMetadata.PluginData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tensorflow.framework.SummaryMetadata.PluginData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tensorflow.framework.SummaryMetadata.PluginData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tensorflow.SummaryMetadata.PluginData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.SummaryMetadata.PluginData)
        org.tensorflow.framework.SummaryMetadata.PluginDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tensorflow.framework.SummaryProtos.internal_static_tensorflow_SummaryMetadata_PluginData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tensorflow.framework.SummaryProtos.internal_static_tensorflow_SummaryMetadata_PluginData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tensorflow.framework.SummaryMetadata.PluginData.class, org.tensorflow.framework.SummaryMetadata.PluginData.Builder.class);
      }

      // Construct using org.tensorflow.framework.SummaryMetadata.PluginData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pluginName_ = "";

        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tensorflow.framework.SummaryProtos.internal_static_tensorflow_SummaryMetadata_PluginData_descriptor;
      }

      public org.tensorflow.framework.SummaryMetadata.PluginData getDefaultInstanceForType() {
        return org.tensorflow.framework.SummaryMetadata.PluginData.getDefaultInstance();
      }

      public org.tensorflow.framework.SummaryMetadata.PluginData build() {
        org.tensorflow.framework.SummaryMetadata.PluginData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tensorflow.framework.SummaryMetadata.PluginData buildPartial() {
        org.tensorflow.framework.SummaryMetadata.PluginData result = new org.tensorflow.framework.SummaryMetadata.PluginData(this);
        result.pluginName_ = pluginName_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tensorflow.framework.SummaryMetadata.PluginData) {
          return mergeFrom((org.tensorflow.framework.SummaryMetadata.PluginData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tensorflow.framework.SummaryMetadata.PluginData other) {
        if (other == org.tensorflow.framework.SummaryMetadata.PluginData.getDefaultInstance()) return this;
        if (!other.getPluginName().isEmpty()) {
          pluginName_ = other.pluginName_;
          onChanged();
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tensorflow.framework.SummaryMetadata.PluginData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tensorflow.framework.SummaryMetadata.PluginData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object pluginName_ = "";
      /**
       * <code>optional string plugin_name = 1;</code>
       *
       * <pre>
       * The name of the plugin this data pertains to.
       * </pre>
       */
      public java.lang.String getPluginName() {
        java.lang.Object ref = pluginName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pluginName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string plugin_name = 1;</code>
       *
       * <pre>
       * The name of the plugin this data pertains to.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPluginNameBytes() {
        java.lang.Object ref = pluginName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pluginName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string plugin_name = 1;</code>
       *
       * <pre>
       * The name of the plugin this data pertains to.
       * </pre>
       */
      public Builder setPluginName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pluginName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string plugin_name = 1;</code>
       *
       * <pre>
       * The name of the plugin this data pertains to.
       * </pre>
       */
      public Builder clearPluginName() {
        
        pluginName_ = getDefaultInstance().getPluginName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string plugin_name = 1;</code>
       *
       * <pre>
       * The name of the plugin this data pertains to.
       * </pre>
       */
      public Builder setPluginNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pluginName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content = 2;</code>
       *
       * <pre>
       * The content to store for the plugin. The best practice is for this to be
       * a binary serialized protocol buffer.
       * </pre>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>optional bytes content = 2;</code>
       *
       * <pre>
       * The content to store for the plugin. The best practice is for this to be
       * a binary serialized protocol buffer.
       * </pre>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content = 2;</code>
       *
       * <pre>
       * The content to store for the plugin. The best practice is for this to be
       * a binary serialized protocol buffer.
       * </pre>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.SummaryMetadata.PluginData)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.SummaryMetadata.PluginData)
    private static final org.tensorflow.framework.SummaryMetadata.PluginData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tensorflow.framework.SummaryMetadata.PluginData();
    }

    public static org.tensorflow.framework.SummaryMetadata.PluginData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PluginData>
        PARSER = new com.google.protobuf.AbstractParser<PluginData>() {
      public PluginData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PluginData(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<PluginData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PluginData> getParserForType() {
      return PARSER;
    }

    public org.tensorflow.framework.SummaryMetadata.PluginData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int PLUGIN_DATA_FIELD_NUMBER = 1;
  private org.tensorflow.framework.SummaryMetadata.PluginData pluginData_;
  /**
   * <code>optional .tensorflow.SummaryMetadata.PluginData plugin_data = 1;</code>
   *
   * <pre>
   * Data that associates a summary with a certain plugin.
   * </pre>
   */
  public boolean hasPluginData() {
    return pluginData_ != null;
  }
  /**
   * <code>optional .tensorflow.SummaryMetadata.PluginData plugin_data = 1;</code>
   *
   * <pre>
   * Data that associates a summary with a certain plugin.
   * </pre>
   */
  public org.tensorflow.framework.SummaryMetadata.PluginData getPluginData() {
    return pluginData_ == null ? org.tensorflow.framework.SummaryMetadata.PluginData.getDefaultInstance() : pluginData_;
  }
  /**
   * <code>optional .tensorflow.SummaryMetadata.PluginData plugin_data = 1;</code>
   *
   * <pre>
   * Data that associates a summary with a certain plugin.
   * </pre>
   */
  public org.tensorflow.framework.SummaryMetadata.PluginDataOrBuilder getPluginDataOrBuilder() {
    return getPluginData();
  }

  public static final int DISPLAY_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object displayName_;
  /**
   * <code>optional string display_name = 2;</code>
   *
   * <pre>
   * Display name for viewing in TensorBoard.
   * </pre>
   */
  public java.lang.String getDisplayName() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      displayName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string display_name = 2;</code>
   *
   * <pre>
   * Display name for viewing in TensorBoard.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getDisplayNameBytes() {
    java.lang.Object ref = displayName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      displayName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUMMARY_DESCRIPTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object summaryDescription_;
  /**
   * <code>optional string summary_description = 3;</code>
   *
   * <pre>
   * Longform readable description of the summary sequence. Markdown supported.
   * </pre>
   */
  public java.lang.String getSummaryDescription() {
    java.lang.Object ref = summaryDescription_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      summaryDescription_ = s;
      return s;
    }
  }
  /**
   * <code>optional string summary_description = 3;</code>
   *
   * <pre>
   * Longform readable description of the summary sequence. Markdown supported.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getSummaryDescriptionBytes() {
    java.lang.Object ref = summaryDescription_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      summaryDescription_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pluginData_ != null) {
      output.writeMessage(1, getPluginData());
    }
    if (!getDisplayNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, displayName_);
    }
    if (!getSummaryDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, summaryDescription_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pluginData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPluginData());
    }
    if (!getDisplayNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, displayName_);
    }
    if (!getSummaryDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, summaryDescription_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static org.tensorflow.framework.SummaryMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.SummaryMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.SummaryMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.SummaryMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.SummaryMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.tensorflow.framework.SummaryMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.tensorflow.framework.SummaryMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.tensorflow.framework.SummaryMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.tensorflow.framework.SummaryMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.tensorflow.framework.SummaryMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.framework.SummaryMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.SummaryMetadata}
   *
   * <pre>
   * A SummaryMetadata encapsulates information on which plugins are able to make
   * use of a certain summary value.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.SummaryMetadata)
      org.tensorflow.framework.SummaryMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.framework.SummaryProtos.internal_static_tensorflow_SummaryMetadata_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.framework.SummaryProtos.internal_static_tensorflow_SummaryMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.framework.SummaryMetadata.class, org.tensorflow.framework.SummaryMetadata.Builder.class);
    }

    // Construct using org.tensorflow.framework.SummaryMetadata.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (pluginDataBuilder_ == null) {
        pluginData_ = null;
      } else {
        pluginData_ = null;
        pluginDataBuilder_ = null;
      }
      displayName_ = "";

      summaryDescription_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.framework.SummaryProtos.internal_static_tensorflow_SummaryMetadata_descriptor;
    }

    public org.tensorflow.framework.SummaryMetadata getDefaultInstanceForType() {
      return org.tensorflow.framework.SummaryMetadata.getDefaultInstance();
    }

    public org.tensorflow.framework.SummaryMetadata build() {
      org.tensorflow.framework.SummaryMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.tensorflow.framework.SummaryMetadata buildPartial() {
      org.tensorflow.framework.SummaryMetadata result = new org.tensorflow.framework.SummaryMetadata(this);
      if (pluginDataBuilder_ == null) {
        result.pluginData_ = pluginData_;
      } else {
        result.pluginData_ = pluginDataBuilder_.build();
      }
      result.displayName_ = displayName_;
      result.summaryDescription_ = summaryDescription_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.framework.SummaryMetadata) {
        return mergeFrom((org.tensorflow.framework.SummaryMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.framework.SummaryMetadata other) {
      if (other == org.tensorflow.framework.SummaryMetadata.getDefaultInstance()) return this;
      if (other.hasPluginData()) {
        mergePluginData(other.getPluginData());
      }
      if (!other.getDisplayName().isEmpty()) {
        displayName_ = other.displayName_;
        onChanged();
      }
      if (!other.getSummaryDescription().isEmpty()) {
        summaryDescription_ = other.summaryDescription_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tensorflow.framework.SummaryMetadata parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tensorflow.framework.SummaryMetadata) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.tensorflow.framework.SummaryMetadata.PluginData pluginData_ = null;
    private com.google.protobuf.SingleFieldBuilder<
        org.tensorflow.framework.SummaryMetadata.PluginData, org.tensorflow.framework.SummaryMetadata.PluginData.Builder, org.tensorflow.framework.SummaryMetadata.PluginDataOrBuilder> pluginDataBuilder_;
    /**
     * <code>optional .tensorflow.SummaryMetadata.PluginData plugin_data = 1;</code>
     *
     * <pre>
     * Data that associates a summary with a certain plugin.
     * </pre>
     */
    public boolean hasPluginData() {
      return pluginDataBuilder_ != null || pluginData_ != null;
    }
    /**
     * <code>optional .tensorflow.SummaryMetadata.PluginData plugin_data = 1;</code>
     *
     * <pre>
     * Data that associates a summary with a certain plugin.
     * </pre>
     */
    public org.tensorflow.framework.SummaryMetadata.PluginData getPluginData() {
      if (pluginDataBuilder_ == null) {
        return pluginData_ == null ? org.tensorflow.framework.SummaryMetadata.PluginData.getDefaultInstance() : pluginData_;
      } else {
        return pluginDataBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .tensorflow.SummaryMetadata.PluginData plugin_data = 1;</code>
     *
     * <pre>
     * Data that associates a summary with a certain plugin.
     * </pre>
     */
    public Builder setPluginData(org.tensorflow.framework.SummaryMetadata.PluginData value) {
      if (pluginDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pluginData_ = value;
        onChanged();
      } else {
        pluginDataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .tensorflow.SummaryMetadata.PluginData plugin_data = 1;</code>
     *
     * <pre>
     * Data that associates a summary with a certain plugin.
     * </pre>
     */
    public Builder setPluginData(
        org.tensorflow.framework.SummaryMetadata.PluginData.Builder builderForValue) {
      if (pluginDataBuilder_ == null) {
        pluginData_ = builderForValue.build();
        onChanged();
      } else {
        pluginDataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .tensorflow.SummaryMetadata.PluginData plugin_data = 1;</code>
     *
     * <pre>
     * Data that associates a summary with a certain plugin.
     * </pre>
     */
    public Builder mergePluginData(org.tensorflow.framework.SummaryMetadata.PluginData value) {
      if (pluginDataBuilder_ == null) {
        if (pluginData_ != null) {
          pluginData_ =
            org.tensorflow.framework.SummaryMetadata.PluginData.newBuilder(pluginData_).mergeFrom(value).buildPartial();
        } else {
          pluginData_ = value;
        }
        onChanged();
      } else {
        pluginDataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .tensorflow.SummaryMetadata.PluginData plugin_data = 1;</code>
     *
     * <pre>
     * Data that associates a summary with a certain plugin.
     * </pre>
     */
    public Builder clearPluginData() {
      if (pluginDataBuilder_ == null) {
        pluginData_ = null;
        onChanged();
      } else {
        pluginData_ = null;
        pluginDataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .tensorflow.SummaryMetadata.PluginData plugin_data = 1;</code>
     *
     * <pre>
     * Data that associates a summary with a certain plugin.
     * </pre>
     */
    public org.tensorflow.framework.SummaryMetadata.PluginData.Builder getPluginDataBuilder() {
      
      onChanged();
      return getPluginDataFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .tensorflow.SummaryMetadata.PluginData plugin_data = 1;</code>
     *
     * <pre>
     * Data that associates a summary with a certain plugin.
     * </pre>
     */
    public org.tensorflow.framework.SummaryMetadata.PluginDataOrBuilder getPluginDataOrBuilder() {
      if (pluginDataBuilder_ != null) {
        return pluginDataBuilder_.getMessageOrBuilder();
      } else {
        return pluginData_ == null ?
            org.tensorflow.framework.SummaryMetadata.PluginData.getDefaultInstance() : pluginData_;
      }
    }
    /**
     * <code>optional .tensorflow.SummaryMetadata.PluginData plugin_data = 1;</code>
     *
     * <pre>
     * Data that associates a summary with a certain plugin.
     * </pre>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.tensorflow.framework.SummaryMetadata.PluginData, org.tensorflow.framework.SummaryMetadata.PluginData.Builder, org.tensorflow.framework.SummaryMetadata.PluginDataOrBuilder> 
        getPluginDataFieldBuilder() {
      if (pluginDataBuilder_ == null) {
        pluginDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.tensorflow.framework.SummaryMetadata.PluginData, org.tensorflow.framework.SummaryMetadata.PluginData.Builder, org.tensorflow.framework.SummaryMetadata.PluginDataOrBuilder>(
                getPluginData(),
                getParentForChildren(),
                isClean());
        pluginData_ = null;
      }
      return pluginDataBuilder_;
    }

    private java.lang.Object displayName_ = "";
    /**
     * <code>optional string display_name = 2;</code>
     *
     * <pre>
     * Display name for viewing in TensorBoard.
     * </pre>
     */
    public java.lang.String getDisplayName() {
      java.lang.Object ref = displayName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string display_name = 2;</code>
     *
     * <pre>
     * Display name for viewing in TensorBoard.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      java.lang.Object ref = displayName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string display_name = 2;</code>
     *
     * <pre>
     * Display name for viewing in TensorBoard.
     * </pre>
     */
    public Builder setDisplayName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      displayName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string display_name = 2;</code>
     *
     * <pre>
     * Display name for viewing in TensorBoard.
     * </pre>
     */
    public Builder clearDisplayName() {
      
      displayName_ = getDefaultInstance().getDisplayName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string display_name = 2;</code>
     *
     * <pre>
     * Display name for viewing in TensorBoard.
     * </pre>
     */
    public Builder setDisplayNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      displayName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object summaryDescription_ = "";
    /**
     * <code>optional string summary_description = 3;</code>
     *
     * <pre>
     * Longform readable description of the summary sequence. Markdown supported.
     * </pre>
     */
    public java.lang.String getSummaryDescription() {
      java.lang.Object ref = summaryDescription_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        summaryDescription_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string summary_description = 3;</code>
     *
     * <pre>
     * Longform readable description of the summary sequence. Markdown supported.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSummaryDescriptionBytes() {
      java.lang.Object ref = summaryDescription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        summaryDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string summary_description = 3;</code>
     *
     * <pre>
     * Longform readable description of the summary sequence. Markdown supported.
     * </pre>
     */
    public Builder setSummaryDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      summaryDescription_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string summary_description = 3;</code>
     *
     * <pre>
     * Longform readable description of the summary sequence. Markdown supported.
     * </pre>
     */
    public Builder clearSummaryDescription() {
      
      summaryDescription_ = getDefaultInstance().getSummaryDescription();
      onChanged();
      return this;
    }
    /**
     * <code>optional string summary_description = 3;</code>
     *
     * <pre>
     * Longform readable description of the summary sequence. Markdown supported.
     * </pre>
     */
    public Builder setSummaryDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      summaryDescription_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.SummaryMetadata)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.SummaryMetadata)
  private static final org.tensorflow.framework.SummaryMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.framework.SummaryMetadata();
  }

  public static org.tensorflow.framework.SummaryMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SummaryMetadata>
      PARSER = new com.google.protobuf.AbstractParser<SummaryMetadata>() {
    public SummaryMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new SummaryMetadata(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<SummaryMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SummaryMetadata> getParserForType() {
    return PARSER;
  }

  public org.tensorflow.framework.SummaryMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

