// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/tensor.proto

package org.tensorflow.framework;

public interface VariantTensorDataProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.VariantTensorDataProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string type_name = 1;</code>
   *
   * <pre>
   * Name of the type of objects being serialized.
   * </pre>
   */
  java.lang.String getTypeName();
  /**
   * <code>optional string type_name = 1;</code>
   *
   * <pre>
   * Name of the type of objects being serialized.
   * </pre>
   */
  com.google.protobuf.ByteString
      getTypeNameBytes();

  /**
   * <code>optional bytes metadata = 2;</code>
   *
   * <pre>
   * Portions of the object that are not Tensors.
   * </pre>
   */
  com.google.protobuf.ByteString getMetadata();

  /**
   * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
   *
   * <pre>
   * Tensors contained within objects being serialized.
   * </pre>
   */
  java.util.List<org.tensorflow.framework.TensorProto> 
      getTensorsList();
  /**
   * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
   *
   * <pre>
   * Tensors contained within objects being serialized.
   * </pre>
   */
  org.tensorflow.framework.TensorProto getTensors(int index);
  /**
   * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
   *
   * <pre>
   * Tensors contained within objects being serialized.
   * </pre>
   */
  int getTensorsCount();
  /**
   * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
   *
   * <pre>
   * Tensors contained within objects being serialized.
   * </pre>
   */
  java.util.List<? extends org.tensorflow.framework.TensorProtoOrBuilder> 
      getTensorsOrBuilderList();
  /**
   * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
   *
   * <pre>
   * Tensors contained within objects being serialized.
   * </pre>
   */
  org.tensorflow.framework.TensorProtoOrBuilder getTensorsOrBuilder(
      int index);
}
