// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/tensor.proto

package org.tensorflow.framework;

/**
 * Protobuf type {@code tensorflow.VariantTensorDataProto}
 *
 * <pre>
 * Protocol buffer representing the serialization format of DT_VARIANT tensors.
 * </pre>
 */
public  final class VariantTensorDataProto extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tensorflow.VariantTensorDataProto)
    VariantTensorDataProtoOrBuilder {
  // Use VariantTensorDataProto.newBuilder() to construct.
  private VariantTensorDataProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private VariantTensorDataProto() {
    typeName_ = "";
    metadata_ = com.google.protobuf.ByteString.EMPTY;
    tensors_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private VariantTensorDataProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            typeName_ = s;
            break;
          }
          case 18: {

            metadata_ = input.readBytes();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              tensors_ = new java.util.ArrayList<org.tensorflow.framework.TensorProto>();
              mutable_bitField0_ |= 0x00000004;
            }
            tensors_.add(input.readMessage(org.tensorflow.framework.TensorProto.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        tensors_ = java.util.Collections.unmodifiableList(tensors_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.tensorflow.framework.TensorProtos.internal_static_tensorflow_VariantTensorDataProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.tensorflow.framework.TensorProtos.internal_static_tensorflow_VariantTensorDataProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.tensorflow.framework.VariantTensorDataProto.class, org.tensorflow.framework.VariantTensorDataProto.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object typeName_;
  /**
   * <code>optional string type_name = 1;</code>
   *
   * <pre>
   * Name of the type of objects being serialized.
   * </pre>
   */
  public java.lang.String getTypeName() {
    java.lang.Object ref = typeName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string type_name = 1;</code>
   *
   * <pre>
   * Name of the type of objects being serialized.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getTypeNameBytes() {
    java.lang.Object ref = typeName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METADATA_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString metadata_;
  /**
   * <code>optional bytes metadata = 2;</code>
   *
   * <pre>
   * Portions of the object that are not Tensors.
   * </pre>
   */
  public com.google.protobuf.ByteString getMetadata() {
    return metadata_;
  }

  public static final int TENSORS_FIELD_NUMBER = 3;
  private java.util.List<org.tensorflow.framework.TensorProto> tensors_;
  /**
   * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
   *
   * <pre>
   * Tensors contained within objects being serialized.
   * </pre>
   */
  public java.util.List<org.tensorflow.framework.TensorProto> getTensorsList() {
    return tensors_;
  }
  /**
   * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
   *
   * <pre>
   * Tensors contained within objects being serialized.
   * </pre>
   */
  public java.util.List<? extends org.tensorflow.framework.TensorProtoOrBuilder> 
      getTensorsOrBuilderList() {
    return tensors_;
  }
  /**
   * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
   *
   * <pre>
   * Tensors contained within objects being serialized.
   * </pre>
   */
  public int getTensorsCount() {
    return tensors_.size();
  }
  /**
   * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
   *
   * <pre>
   * Tensors contained within objects being serialized.
   * </pre>
   */
  public org.tensorflow.framework.TensorProto getTensors(int index) {
    return tensors_.get(index);
  }
  /**
   * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
   *
   * <pre>
   * Tensors contained within objects being serialized.
   * </pre>
   */
  public org.tensorflow.framework.TensorProtoOrBuilder getTensorsOrBuilder(
      int index) {
    return tensors_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTypeNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, typeName_);
    }
    if (!metadata_.isEmpty()) {
      output.writeBytes(2, metadata_);
    }
    for (int i = 0; i < tensors_.size(); i++) {
      output.writeMessage(3, tensors_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTypeNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, typeName_);
    }
    if (!metadata_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, metadata_);
    }
    for (int i = 0; i < tensors_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, tensors_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static org.tensorflow.framework.VariantTensorDataProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.VariantTensorDataProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.VariantTensorDataProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.tensorflow.framework.VariantTensorDataProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.tensorflow.framework.VariantTensorDataProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.tensorflow.framework.VariantTensorDataProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.tensorflow.framework.VariantTensorDataProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.tensorflow.framework.VariantTensorDataProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.tensorflow.framework.VariantTensorDataProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.tensorflow.framework.VariantTensorDataProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.tensorflow.framework.VariantTensorDataProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tensorflow.VariantTensorDataProto}
   *
   * <pre>
   * Protocol buffer representing the serialization format of DT_VARIANT tensors.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tensorflow.VariantTensorDataProto)
      org.tensorflow.framework.VariantTensorDataProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tensorflow.framework.TensorProtos.internal_static_tensorflow_VariantTensorDataProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tensorflow.framework.TensorProtos.internal_static_tensorflow_VariantTensorDataProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tensorflow.framework.VariantTensorDataProto.class, org.tensorflow.framework.VariantTensorDataProto.Builder.class);
    }

    // Construct using org.tensorflow.framework.VariantTensorDataProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getTensorsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      typeName_ = "";

      metadata_ = com.google.protobuf.ByteString.EMPTY;

      if (tensorsBuilder_ == null) {
        tensors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        tensorsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.tensorflow.framework.TensorProtos.internal_static_tensorflow_VariantTensorDataProto_descriptor;
    }

    public org.tensorflow.framework.VariantTensorDataProto getDefaultInstanceForType() {
      return org.tensorflow.framework.VariantTensorDataProto.getDefaultInstance();
    }

    public org.tensorflow.framework.VariantTensorDataProto build() {
      org.tensorflow.framework.VariantTensorDataProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.tensorflow.framework.VariantTensorDataProto buildPartial() {
      org.tensorflow.framework.VariantTensorDataProto result = new org.tensorflow.framework.VariantTensorDataProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.typeName_ = typeName_;
      result.metadata_ = metadata_;
      if (tensorsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          tensors_ = java.util.Collections.unmodifiableList(tensors_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.tensors_ = tensors_;
      } else {
        result.tensors_ = tensorsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.tensorflow.framework.VariantTensorDataProto) {
        return mergeFrom((org.tensorflow.framework.VariantTensorDataProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.tensorflow.framework.VariantTensorDataProto other) {
      if (other == org.tensorflow.framework.VariantTensorDataProto.getDefaultInstance()) return this;
      if (!other.getTypeName().isEmpty()) {
        typeName_ = other.typeName_;
        onChanged();
      }
      if (other.getMetadata() != com.google.protobuf.ByteString.EMPTY) {
        setMetadata(other.getMetadata());
      }
      if (tensorsBuilder_ == null) {
        if (!other.tensors_.isEmpty()) {
          if (tensors_.isEmpty()) {
            tensors_ = other.tensors_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTensorsIsMutable();
            tensors_.addAll(other.tensors_);
          }
          onChanged();
        }
      } else {
        if (!other.tensors_.isEmpty()) {
          if (tensorsBuilder_.isEmpty()) {
            tensorsBuilder_.dispose();
            tensorsBuilder_ = null;
            tensors_ = other.tensors_;
            bitField0_ = (bitField0_ & ~0x00000004);
            tensorsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTensorsFieldBuilder() : null;
          } else {
            tensorsBuilder_.addAllMessages(other.tensors_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.tensorflow.framework.VariantTensorDataProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.tensorflow.framework.VariantTensorDataProto) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object typeName_ = "";
    /**
     * <code>optional string type_name = 1;</code>
     *
     * <pre>
     * Name of the type of objects being serialized.
     * </pre>
     */
    public java.lang.String getTypeName() {
      java.lang.Object ref = typeName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string type_name = 1;</code>
     *
     * <pre>
     * Name of the type of objects being serialized.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTypeNameBytes() {
      java.lang.Object ref = typeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string type_name = 1;</code>
     *
     * <pre>
     * Name of the type of objects being serialized.
     * </pre>
     */
    public Builder setTypeName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      typeName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string type_name = 1;</code>
     *
     * <pre>
     * Name of the type of objects being serialized.
     * </pre>
     */
    public Builder clearTypeName() {
      
      typeName_ = getDefaultInstance().getTypeName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string type_name = 1;</code>
     *
     * <pre>
     * Name of the type of objects being serialized.
     * </pre>
     */
    public Builder setTypeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      typeName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString metadata_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes metadata = 2;</code>
     *
     * <pre>
     * Portions of the object that are not Tensors.
     * </pre>
     */
    public com.google.protobuf.ByteString getMetadata() {
      return metadata_;
    }
    /**
     * <code>optional bytes metadata = 2;</code>
     *
     * <pre>
     * Portions of the object that are not Tensors.
     * </pre>
     */
    public Builder setMetadata(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      metadata_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes metadata = 2;</code>
     *
     * <pre>
     * Portions of the object that are not Tensors.
     * </pre>
     */
    public Builder clearMetadata() {
      
      metadata_ = getDefaultInstance().getMetadata();
      onChanged();
      return this;
    }

    private java.util.List<org.tensorflow.framework.TensorProto> tensors_ =
      java.util.Collections.emptyList();
    private void ensureTensorsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        tensors_ = new java.util.ArrayList<org.tensorflow.framework.TensorProto>(tensors_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.tensorflow.framework.TensorProto, org.tensorflow.framework.TensorProto.Builder, org.tensorflow.framework.TensorProtoOrBuilder> tensorsBuilder_;

    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public java.util.List<org.tensorflow.framework.TensorProto> getTensorsList() {
      if (tensorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tensors_);
      } else {
        return tensorsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public int getTensorsCount() {
      if (tensorsBuilder_ == null) {
        return tensors_.size();
      } else {
        return tensorsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public org.tensorflow.framework.TensorProto getTensors(int index) {
      if (tensorsBuilder_ == null) {
        return tensors_.get(index);
      } else {
        return tensorsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public Builder setTensors(
        int index, org.tensorflow.framework.TensorProto value) {
      if (tensorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTensorsIsMutable();
        tensors_.set(index, value);
        onChanged();
      } else {
        tensorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public Builder setTensors(
        int index, org.tensorflow.framework.TensorProto.Builder builderForValue) {
      if (tensorsBuilder_ == null) {
        ensureTensorsIsMutable();
        tensors_.set(index, builderForValue.build());
        onChanged();
      } else {
        tensorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public Builder addTensors(org.tensorflow.framework.TensorProto value) {
      if (tensorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTensorsIsMutable();
        tensors_.add(value);
        onChanged();
      } else {
        tensorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public Builder addTensors(
        int index, org.tensorflow.framework.TensorProto value) {
      if (tensorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTensorsIsMutable();
        tensors_.add(index, value);
        onChanged();
      } else {
        tensorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public Builder addTensors(
        org.tensorflow.framework.TensorProto.Builder builderForValue) {
      if (tensorsBuilder_ == null) {
        ensureTensorsIsMutable();
        tensors_.add(builderForValue.build());
        onChanged();
      } else {
        tensorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public Builder addTensors(
        int index, org.tensorflow.framework.TensorProto.Builder builderForValue) {
      if (tensorsBuilder_ == null) {
        ensureTensorsIsMutable();
        tensors_.add(index, builderForValue.build());
        onChanged();
      } else {
        tensorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public Builder addAllTensors(
        java.lang.Iterable<? extends org.tensorflow.framework.TensorProto> values) {
      if (tensorsBuilder_ == null) {
        ensureTensorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tensors_);
        onChanged();
      } else {
        tensorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public Builder clearTensors() {
      if (tensorsBuilder_ == null) {
        tensors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        tensorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public Builder removeTensors(int index) {
      if (tensorsBuilder_ == null) {
        ensureTensorsIsMutable();
        tensors_.remove(index);
        onChanged();
      } else {
        tensorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public org.tensorflow.framework.TensorProto.Builder getTensorsBuilder(
        int index) {
      return getTensorsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public org.tensorflow.framework.TensorProtoOrBuilder getTensorsOrBuilder(
        int index) {
      if (tensorsBuilder_ == null) {
        return tensors_.get(index);  } else {
        return tensorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public java.util.List<? extends org.tensorflow.framework.TensorProtoOrBuilder> 
         getTensorsOrBuilderList() {
      if (tensorsBuilder_ != null) {
        return tensorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tensors_);
      }
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public org.tensorflow.framework.TensorProto.Builder addTensorsBuilder() {
      return getTensorsFieldBuilder().addBuilder(
          org.tensorflow.framework.TensorProto.getDefaultInstance());
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public org.tensorflow.framework.TensorProto.Builder addTensorsBuilder(
        int index) {
      return getTensorsFieldBuilder().addBuilder(
          index, org.tensorflow.framework.TensorProto.getDefaultInstance());
    }
    /**
     * <code>repeated .tensorflow.TensorProto tensors = 3;</code>
     *
     * <pre>
     * Tensors contained within objects being serialized.
     * </pre>
     */
    public java.util.List<org.tensorflow.framework.TensorProto.Builder> 
         getTensorsBuilderList() {
      return getTensorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.tensorflow.framework.TensorProto, org.tensorflow.framework.TensorProto.Builder, org.tensorflow.framework.TensorProtoOrBuilder> 
        getTensorsFieldBuilder() {
      if (tensorsBuilder_ == null) {
        tensorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.tensorflow.framework.TensorProto, org.tensorflow.framework.TensorProto.Builder, org.tensorflow.framework.TensorProtoOrBuilder>(
                tensors_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        tensors_ = null;
      }
      return tensorsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:tensorflow.VariantTensorDataProto)
  }

  // @@protoc_insertion_point(class_scope:tensorflow.VariantTensorDataProto)
  private static final org.tensorflow.framework.VariantTensorDataProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.tensorflow.framework.VariantTensorDataProto();
  }

  public static org.tensorflow.framework.VariantTensorDataProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VariantTensorDataProto>
      PARSER = new com.google.protobuf.AbstractParser<VariantTensorDataProto>() {
    public VariantTensorDataProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new VariantTensorDataProto(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<VariantTensorDataProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VariantTensorDataProto> getParserForType() {
    return PARSER;
  }

  public org.tensorflow.framework.VariantTensorDataProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

